sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  qiniu:
    accessKey: 0cGoFjREJRCTVDjZZMO-tTCmwnLN-aik33hNPosr
    secretKey: 094elNxD1A5u37ORTS2_wXBs3Opz5IGvXnIx58Fp
    bucket: itheimacangqiong
    hostName: http://tf228sotp.hd-bkt.clouddn.com
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxd165c88947111264
    secret: ac3b1afa1b734ef071d56917e0606243
